[package]
name = "basalt-lib"
version = "1.0.0"
entrypoint = "src/exports.typ"
authors = ["Gabriel Talbert Bunt"]
license = "AGPL"
description = "Library to power Basalt, a knowledge management tool."
repository = "https://github.com/GabrielDTB/basalt-lib"
keywords = [
  "basalt",
  "knowledge-management",
  "notes",
  "notetaking",
]
